
server:
  port: 8200
  servlet:
    context-path: /uaa

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: oauth
  thymeleaf:
    cache: false  #关闭thymeleaf缓存 开发时使用 否则没有实时画面
#    check-template-location: true    # 检查模板是否存在，然后再呈现
#    mode: HTML5
#    prefix: classpath:/templates/
#    suffix: .html
#    servlet:
#      content-type: text/html
info:
  version: "0.1.0"
logging:
  level:
    root: INFO
    org.springframework.web: INFO
  file: oauth.log
hystrix:
  shareSecurityContext: true

ribbon:
  eager-load:
    enabled: true
    clients: feign


  #pattern:
    #file: "%d{yyyy/MM/dd } - %msg%n"





